version: '3.1'
services:
    webserver:
        image: 'nginx:alpine'
        networks:
            - network1
        volumes:
            - '.:/application'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '64000:80'
        depends_on:
            - php-fpm

    php-fpm:
        build: phpdocker/php-fpm
        networks:
            - network1
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8.0'
        networks:
            - network1
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root_pass
            - MYSQL_DATABASE=db
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=app_pass
        ports:
            - '64002:3306'

volumes:
  # So that sites aren't wiped every time containers are restarted, MySQL uses a persistent volume.
  mysql: {}

networks:
  # The network allows to connect between containers using their service name.
  network1:
    driver: bridge
